title: Borderlands SDK Developer Docs

url: https://bl-sdk.github.io

markdown: kramdown
theme: just-the-docs

color_scheme: dev

defaults:
  - scope:
      path: ""
      type: willow1_mods
    values:
      layout: mod
  - scope:
      path: ""
      type: willow2_mods
    values:
      layout: mod
  - scope:
      path: ""
      type: oak_mods
    values:
      layout: mod
  - scope:
      path: ""
    values:
      has_toc: false

callouts:
  warning:
    title: Warning
    color: red

favicon_ico: /assets/images/favicon.png

plugins:
  - jekyll-commonmark-ghpages
  - jekyll-default-layout
  - jekyll-include-cache
  - jekyll-optional-front-matter
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-redirect-from

optional_front_matter:
  remove_originals: true

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

  - Readme.md

  - oak-mod-db
  - willow1-mod-db
  - willow2-mod-db

nav_external_links:
  - title: BL1 Mods
    url: willow1-mod-db/
  - title: BL2/TPS/AoDK Mods
    url: willow2-mod-db/
  - title: BL3/WL Mods
    url: oak-mod-db/
  - title: Modding Support Discord
    url: https://discord.gg/bXeqV8Ef9R
  - title: SDK Developer Discord
    url: https://discord.gg/VJXtHvh
